---
- name: Add user
  user: name={{ user }} password="{{ password }}" shell=/bin/bash

- name: Add user to sudoers
  lineinfile: dest=/etc/sudoers
              regexp="{{ user }} ALL"
              line="{{ user }} ALL=(ALL) ALL"
              state=present

- name: Change root password
  user: name={{ user }} password="{{ root_password }}"
