---
- name: Install Postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib

- name: Copy backup script
  template: 
    src: backup_postgres.j2
    dest: /usr/local/sbin/backup_postgres.sh
    owner: root
    group: root
    mode: "u+rwx,g+r,o+r"

- name: Copy backup rotation config
  template: 
    src: postgres-backup-rotation.j2
    dest: "{{postgres_backup_rotation_conf}}"
    owner: root
    group: root
    mode: 0644

- name: Setup cron job 
  cron:
    name: postgres backup
    minute: "45"
    hour: "3"
    job: "/usr/local/sbin/backup_postgres.sh"

- name: Add entry to backup file list
  lineinfile:
    dest: "{{ backup_include_filelist }}"
    line: "{{ postgres_backup_dir }}"
    create: yes
